
version: '3.1'

volumes:
  mongo_data:

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "user"
    volumes:
        - ./mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "user"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "user"

  web:
    build: .
    image: gowebapp
    restart: always
    ports:
      - 4747:4747
    links:
      - mongo
    env_file:
      - .env