name: Push image to ecr
on:
  release:
    types: [published]   
jobs:
  sensoris-s3-ecr:                           
    name: push to s3                         
    runs-on: ubuntu-latest                           
    steps:          
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.SENSORIS_PAT }}
        submodules: recursive 

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sensoris_tools

    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-1
        local-image: sensoris_tools
        image: sensoris_tools:${{ github.event.release.tag_name }}

    - name: Save docker image
      run: docker save sensoris_tools:latest | gzip > sensoris_tools.tar.gz

    - name: Create folder
      run: mkdir sensoris_cli

    - name: Zip sample files
      uses: papeloto/action-zip@v1
      with:
        files: samples/
        dest: samples.zip

    - name: Zip all files
      uses: papeloto/action-zip@v1
      with:
        files: samples.zip README.md sensoris_tools.tar.gz
        dest: sensoris_cli/sensoris_tools.zip  

    - name: Upload file to bucket
      uses: zdurham/s3-upload-github-action@master
      env:
        FILE: ./sensoris_cli/sensoris_tools.zip 
        AWS_REGION: 'us-west-1'
        S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        S3_KEY: sensoris_tools.zip
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}